// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA181En628VyCKdTfDsditZ_ZJ56rah4Ho',
    appId: '1:593293559977:web:5c424679af47abb12c41b8',
    messagingSenderId: '593293559977',
    projectId: 'humanlibrary-1c35f',
    authDomain: 'humanlibrary-1c35f.firebaseapp.com',
    storageBucket: 'humanlibrary-1c35f.appspot.com',
    measurementId: 'G-FQ114Q07K4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdmugOeS8mphdf4CpQZKk89YIm5PXoIMQ',
    appId: '1:593293559977:android:8f66de39d44a15932c41b8',
    messagingSenderId: '593293559977',
    projectId: 'humanlibrary-1c35f',
    storageBucket: 'humanlibrary-1c35f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS6oppJyacUjZmVLce4TcheCCEEU59H8s',
    appId: '1:593293559977:ios:4bfaacfa8dc41a0d2c41b8',
    messagingSenderId: '593293559977',
    projectId: 'humanlibrary-1c35f',
    storageBucket: 'humanlibrary-1c35f.appspot.com',
    iosBundleId: 'com.example.myEcomApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS6oppJyacUjZmVLce4TcheCCEEU59H8s',
    appId: '1:593293559977:ios:4bfaacfa8dc41a0d2c41b8',
    messagingSenderId: '593293559977',
    projectId: 'humanlibrary-1c35f',
    storageBucket: 'humanlibrary-1c35f.appspot.com',
    iosBundleId: 'com.example.myEcomApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA181En628VyCKdTfDsditZ_ZJ56rah4Ho',
    appId: '1:593293559977:web:096c008fd58f74652c41b8',
    messagingSenderId: '593293559977',
    projectId: 'humanlibrary-1c35f',
    authDomain: 'humanlibrary-1c35f.firebaseapp.com',
    storageBucket: 'humanlibrary-1c35f.appspot.com',
    measurementId: 'G-S118P1LG0C',
  );
}
